GET http://localhost:5000/api/news

###

POST http://localhost:5000/api/news
Content-Type: application/json

# {
#      "news_id" : "1111",
#       "news_title" : "CRA-latest",
#       "info": "4.3.2"
# }

###

DELETE http://localhost:5000/api/news/5f241037fffb4d1c88985c78


###

PUT http://localhost:5000/api/news/5f241037fffb4d1c88985c78
Content-Type: application/json

# {
#      "news_id" : "1111",
#       "news_title" : "CRA-latest Update",
#       "info": "4.3.3"
# }

###

GET http://localhost:5000/api/news/id